[metadata]
buildPrefix	= "extra-x86_64-build"
maintainer	= "exampleUser"

[[depends]]
pkgname		= "portable"
sourceType	= "repo"
source		= "archlinuxcn"

[[depends]]
pkgname		= "linuxqq"
sourceType	= "aur"
source		= "https://aur.archlinux.org/linuxqq.git"