[metadata]
# Optional
# The command to build a package. Should be "extra-x86_64-build" or "archlinuxcn-x86_64-build"
#buildPrefix	= "extra-x86_64-build"

# The package type. Can be repo or build. Defines whether this package is pre-built or not. Defaults to "build"
type = "build"
# A full repo/pkgname name to download package from if metaadata.type is repo.
#repo = ""

# Your GitHub user name
maintainer	= "exampleUser"

# A dependency tree. Depth can be 1 to infinity (whoa)
[[depends]]
# Optional
#buildPrefix	= "extra-x86_64-build"

# The package name of a dependency
pkgname		= "portable-packer"

# Source can be either a string of git URL (type git), or repo name (type repo) to download from locally defined repositories.
sourceType	= "repo"
source		= "archlinuxcn"

# Nested dependency.
#[[depends.depends]]
#pkgname	= "lib32-mesa"
#sourceType	= "repo"
#source		= "multilib"

# Nested dependency of the previous dependency
#[[depends.depends.depends]]
#pkgname	= "mesa"
#sourceType	= "repo"
#source		= "multilib"

# A new dependency tree
[[depends]]
# Optional
#buildPrefix	= "extra-x86_64-build"
pkgname		= "linuxqq"
sourceType	= "aur"
source		= "https://aur.archlinux.org/linuxqq.git"

# Install the package on the host as dependency
install		= false